### ISSUE TITLE
Only Uploaded error

### ISSUE THREAD

**Issue by kertase** [openstreetview/upload-scripts#15]
Hi,

When I try uploading with upload_photos_by_exif.py   the only thing I get is:

No sequence file existing
Found 47 pictures to upload
 Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Uploaded error
Finish uploading form dir:  with sequence id: 14568

What am i doing wrong?

**Comment by bogdan-telenav** [comment]
@kertase hi can you provide us a link with some samples with your images.
Thanks

**Comment by kertase** [comment]
Well you will find a sample here: http://3d4pi-avenches.alsenet.com/panos/
Normally to upload to services like yours I still add some extra metadata such as Orientation and XMP data for panoramas if they are need but since I did not find documentation on the needed tags I was going to look into it…

**Comment by bogdan-telenav** [comment]
Hi i think the problem are the panoramas photos... Can you try with normal photos to upload? Thanks for reporting. 
I'm keep going to investigate this issue and when we solve it i'l let you know
Thanks again 👍

**Comment by kertase** [comment]
First of what are you maximum size upload limits?

What kind of support do you have support for panoramas?

What tags do you use and would be nice for you for them to be present in the image metadata?

Unfortunately I could not find any documentation answering those questions…

**Comment by kertase** [comment]
Hi,

Could you tell me please at least what upload size limits you have on   your servers?


Or point me towards the documentation that could tell me?

Thanks you very much

K.

**Comment by bogdan-telenav** [comment]
Hi sorry for late response.

In the next 2 weeks we will publish the documentation.
However maximum file size: 20mb/photo  
If i can help you with anything let me know.

Thanks for reporting
