### ISSUE TITLE
Error with "upload_video.py" and track.txt generated with OSV app v1.4.4(2) 

### ISSUE THREAD

**Issue by Bch78** [openstreetview/upload-scripts#19]
A new version of the OSV application has been delivered today: 
==> version v1.4.4(2).

A try to use the upload_video.py script with a track generated with app v1.4.4 is aborted with the error:

_"Processing directory: 14763xxxxxxx
Metadata backup found
An error has appeared in track.txt
An error has appeared in track.txt
Traceback (most recent call last):
  File "/Users/xxxxx/Documents/Programmation/OpenStreetView/upload-scripts-master/upload_osv_videos/upload_video.py", line 398, in <module>    main(sys.argv[1:])
  File "/Users/xxxxx/Documents/Programmation/OpenStreetView/upload-scripts-master/upload_osv_videos/upload_video.py", line 282, in main
    'sequenceId': id_sequence
UnboundLocalError: local variable 'id_sequence' referenced before assignment"_

A look inside the track.txt generated with v1.4.4 shows that a new format has been identified
_unknown;10.0.2;**1.1.2**;1.4.4(2)_ 
==> new format identification is **1.1.2**

The code in upload_video.py only considers that format may have values 1.1 or 1.1.1:
=> it is why the error occurs

Regards

**Comment by bogdan-telenav** [comment]
Thanks for reporting 👍 
Aded new versions into python script
